package com.dedicatus.VroidViewer.vrm

internal val visemeMappings: Map<String, List<String>> = mapOf(
    "aa" to listOf("fcl_mth_a", "mth_a", "mouth_a", "vowel_a", "jawOpen", "viseme_aa", "vowelA", "Fcl_MTH_A"),
    "ih" to listOf("fcl_mth_i", "mth_i", "mouth_i", "vowel_i", "viseme_ih", "vowelI", "Fcl_MTH_I"),
    "ou" to listOf("fcl_mth_u", "mth_u", "mouth_u", "vowel_u", "viseme_ou", "vowelU", "Fcl_MTH_U"),
    "ee" to listOf("fcl_mth_e", "mth_e", "mouth_e", "vowel_e", "viseme_ee", "vowelE", "Fcl_MTH_E"),
    "oh" to listOf("fcl_mth_o", "mth_o", "mouth_o", "vowel_o", "viseme_oh", "vowelO", "Fcl_MTH_O")
)

internal val expressionMapping: Map<String, List<String>> = mapOf(
    "happy" to listOf("joy", "fun", "happy"),
    "angry" to listOf("angry"),
    "sad" to listOf("sorrow", "sad"),
    "surprised" to listOf("surprised"),
    "relaxed" to listOf("neutral", "relaxed"),
    "blink" to listOf("blink", "close"),
    "aa" to listOf("fcl_mth_a", "vowel_a", "mth_a", "mouth_a", "jawOpen", "viseme_aa", "vowelA"),
    "ih" to listOf("fcl_mth_i", "vowel_i", "mth_i", "mouth_i", "viseme_ih", "vowelI"),
    "ou" to listOf("fcl_mth_u", "vowel_u", "mth_u", "mouth_u", "viseme_ou", "vowelU"),
    "ee" to listOf("fcl_mth_e", "vowel_e", "mth_e", "mouth_e", "viseme_ee", "vowelE"),
    "oh" to listOf("fcl_mth_o", "vowel_o", "mth_o", "mouth_o", "viseme_oh", "vowelO"),
    "jaw" to listOf("jaw", "jawOpen", "fcl_mth_a"), // Support common jaw targets
)

internal val fallbackBonePatterns: Map<String, List<String>> = mapOf(
    "jaw" to listOf("jaw", "ago", "kuchisita", "lower_face", "j_bip_c_jaw", "under_head", "mouth_bone", "j_adj_c_face_mouth", "root_mouth", "head_base"),
    "hips" to listOf("hips", "pelvis"),
    "spine" to listOf("spine"),
    "chest" to listOf("chest"),
    "upperchest" to listOf("upperchest", "upper_chest"),
    "neck" to listOf("neck"),
    "head" to listOf("head"),
    "lefteye" to listOf("lefteye", "eye_l", "eye.l"),
    "righteye" to listOf("righteye", "eye_r", "eye.r"),
    "leftshoulder" to listOf("leftshoulder", "shoulder_l"),
    "rightshoulder" to listOf("rightshoulder", "shoulder_r"),
    "leftupperarm" to listOf("_l_upperarm", "leftupperarm", "upperarm_l"),
    "rightupperarm" to listOf("_r_upperarm", "rightupperarm", "upperarm_r"),
    "leftlowerarm" to listOf("_l_lowerarm", "leftlowerarm", "lowerarm_l"),
    "rightlowerarm" to listOf("_r_lowerarm", "rightlowerarm", "lowerarm_r"),
    "lefthand" to listOf("_l_hand", "lefthand", "hand_l"),
    "righthand" to listOf("_r_hand", "righthand", "hand_r"),
    "leftfoot" to listOf("leftfoot", "foot_l", "l_foot", "left_foot", "ankle_l", "leftankle"),
    "rightfoot" to listOf("rightfoot", "foot_r", "r_foot", "right_foot", "ankle_r", "rightankle"),
    "leftthumbmetacarpal" to listOf("leftthumbmetacarpal", "l_thumb1", "thumb1_l", "thumb_01_l"),
    "leftthumbproximal" to listOf("leftthumbproximal", "l_thumb2", "thumb2_l", "thumb_02_l"),
    "leftthumbdistal" to listOf("leftthumbdistal", "l_thumb3", "thumb3_l", "thumb_03_l"),
    "leftindexproximal" to listOf("leftindexproximal", "l_index1", "index1_l", "index_01_l"),
    "leftindexintermediate" to listOf("leftindexintermediate", "l_index2", "index2_l", "index_02_l"),
    "leftindexdistal" to listOf("leftindexdistal", "l_index3", "index3_l", "index_03_l"),
    "leftmiddleproximal" to listOf("leftmiddleproximal", "l_middle1", "middle1_l", "middle_01_l"),
    "leftmiddleintermediate" to listOf("leftmiddleintermediate", "l_middle2", "middle2_l", "middle_02_l"),
    "leftmiddledistal" to listOf("leftmiddledistal", "l_middle3", "middle3_l", "middle_03_l"),
    "leftringproximal" to listOf("leftringproximal", "l_ring1", "ring1_l", "ring_01_l"),
    "leftringintermediate" to listOf("leftringintermediate", "l_ring2", "ring2_l", "ring_02_l"),
    "leftringdistal" to listOf("leftringdistal", "l_ring3", "ring3_l", "ring_03_l"),
    "leftlittleproximal" to listOf("leftlittleproximal", "leftpinkyproximal", "l_pinky1", "pinky1_l", "little1_l", "little_01_l"),
    "leftlittleintermediate" to listOf("leftlittleintermediate", "leftpinkyintermediate", "l_pinky2", "pinky2_l", "little2_l", "little_02_l"),
    "leftlittledistal" to listOf("leftlittledistal", "leftpinkydistal", "l_pinky3", "pinky3_l", "little3_l", "little_03_l"),
    "rightthumbmetacarpal" to listOf("rightthumbmetacarpal", "r_thumb1", "thumb1_r", "thumb_01_r"),
    "rightthumbproximal" to listOf("rightthumbproximal", "r_thumb2", "thumb2_r", "thumb_02_r"),
    "rightthumbdistal" to listOf("rightthumbdistal", "r_thumb3", "thumb3_r", "thumb_03_r"),
    "rightindexproximal" to listOf("rightindexproximal", "r_index1", "index1_r", "index_01_r"),
    "rightindexintermediate" to listOf("rightindexintermediate", "r_index2", "index2_r", "index_02_r"),
    "rightindexdistal" to listOf("rightindexdistal", "r_index3", "index3_r", "index_03_r"),
    "rightmiddleproximal" to listOf("rightmiddleproximal", "r_middle1", "middle1_r", "middle_01_r"),
    "rightmiddleintermediate" to listOf("rightmiddleintermediate", "r_middle2", "middle2_r", "middle_02_r"),
    "rightmiddledistal" to listOf("rightmiddledistal", "r_middle3", "middle3_r", "middle_03_r"),
    "rightringproximal" to listOf("rightringproximal", "r_ring1", "ring1_r", "ring_01_r"),
    "rightringintermediate" to listOf("rightringintermediate", "r_ring2", "ring2_r", "ring_02_r"),
    "rightringdistal" to listOf("rightringdistal", "r_ring3", "ring3_r", "ring_03_r"),
    "rightlittleproximal" to listOf("rightlittleproximal", "rightpinkyproximal", "r_pinky1", "pinky1_r", "little1_r", "little_01_r"),
    "rightlittleintermediate" to listOf("rightlittleintermediate", "rightpinkyintermediate", "r_pinky2", "pinky2_r", "little2_r", "little_02_r"),
    "rightlittledistal" to listOf("rightlittledistal", "r_pinky3", "pinky3_r", "little3_r", "little_03_r"),
    "leftupperleg" to listOf("_l_upperleg", "leftupperleg", "upperleg_l"),
    "rightupperleg" to listOf("_r_upperleg", "rightupperleg", "upperleg_r"),
    "leftlowerleg" to listOf("_l_lowerleg", "leftlowerleg", "lowerleg_l"),
    "rightlowerleg" to listOf("_r_lowerleg", "rightlowerleg", "lowerleg_r"),
    "leftfoot" to listOf("_l_foot", "leftfoot", "foot_l"),
    "rightfoot" to listOf("_r_foot", "rightfoot", "foot_r"),
)
